# Generated by Django 4.1 on 2022-08-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mob_num',
            new_name='phone_number',
        ),
    ]
